dist: trusty

language: python

python:
  - "2.7"

env:
  fast_finish: true

before_install:
  - env | sort

install:
  - cp pypirc ~/.pypirc
  - sed -ri "s/\{\{.user\}\}/$PYPI_USER/" ~/.pypirc
  - sed -ri "s/\{\{.password\}\}/$PYPI_PASSWORD/" ~/.pypirc
  - chmod 0600 ~/.pypirc
  - cat ~/.pypirc
  - pip install -r requirements.txt

script:
  - python setup.py sdist upload
