dist: trusty

language: python

python:
  - "2.7"

env:
  fast_finish: true

before_install:
  - env

install:
  - cp pypirc ~/.pypirc
  - sed -ri "s/{{.password}}/$PYPI_PASSWORD/" ~/.pypirc
  - pip install --user -r requirements.txt

script:
  - python setup.py dist upload
