dist: trusty

language: python

python:
  - "2.7"

env:
  fast_finish: true

install:
  - pip install -r requirements.txt

script:
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
